=== yasir2000/Research/PetShop/Eclipse/eclipse/plugins/com.omondo.uml.jee_1.4.0.v20090618/XMLConfig/ProfLibMapping/ProfIdConf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 U (http://www.altova.com) by zizou (omondo) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="XML_PACKAGE_ID_CONF">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="AndroMDAVersion" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Presentation">
								<xs:complexType>
									<xs:attribute name="IdProfile" type="xs:string" use="optional"/>
									<xs:attribute name="idAnno" type="xs:string" use="optional"/>
									<xs:attribute name="IdModel" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedPackage" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedProfile"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Service">
								<xs:complexType>
									<xs:attribute name="IdProfile" type="xs:string" use="optional"/>
									<xs:attribute name="idAnno" type="xs:string" use="optional"/>
									<xs:attribute name="IdModel" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedPackage" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedProfile"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Webservice">
								<xs:complexType>
									<xs:attribute name="IdProfile" type="xs:string" use="optional"/>
									<xs:attribute name="idAnno" type="xs:string" use="optional"/>
									<xs:attribute name="IdModel" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedPackage" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedProfile"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Process">
								<xs:complexType>
									<xs:attribute name="IdProfile" type="xs:string" use="optional"/>
									<xs:attribute name="idAnno" type="xs:string" use="optional"/>
									<xs:attribute name="IdModel" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedPackage" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedProfile"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Xml">
								<xs:complexType>
									<xs:attribute name="IdProfile" type="xs:string" use="optional"/>
									<xs:attribute name="idAnno" type="xs:string" use="optional"/>
									<xs:attribute name="IdModel" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedPackage" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedProfile"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Common">
								<xs:complexType>
									<xs:attribute name="IdProfile" type="xs:string" use="optional"/>
									<xs:attribute name="idAnno" type="xs:string" use="optional"/>
									<xs:attribute name="IdModel" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedPackage" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedProfile"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Meta">
								<xs:complexType>
									<xs:attribute name="IdProfile" type="xs:string" use="optional"/>
									<xs:attribute name="idAnno" type="xs:string" use="optional"/>
									<xs:attribute name="IdModel" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedPackage" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedProfile"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Persistance">
								<xs:complexType>
									<xs:attribute name="IdProfile" type="xs:string" use="optional"/>
									<xs:attribute name="idAnno" type="xs:string" use="optional"/>
									<xs:attribute name="IdModel" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedPackage" type="xs:string" use="optional"/>
									<xs:attribute name="ImportedProfile"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="version" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yasir2000/Research/PetShop/Eclipse/eclipse/plugins/com.omondo.uml.jee_1.4.0.v20090618/XMLConfig/ProfLibMapping/AndroIdConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<XML_PACKAGE_ID_CONF xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\Med Zied Ben Ghorbel\Bureau\xmlConfig\ProfLibMapping\ProfIdConf.xsd">
	<AndroMDAVersion version="3.3-SNAPSHOT">
	
		<Presentation  IdProfile="_nQDng_M1EduRCfi1u_r5eA" idAnno="_nQDnhPM1EduRCfi1u_r5eA" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-presentation/3.3-SNAPSHOT/andromda-profile-presentation-3.3-SNAPSHOT.uml2#_jlv-AGprEdummsSofer0Pg" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-presentation/3.3-SNAPSHOT/andromda-profile-presentation-3.3-SNAPSHOT.uml2#_jlv-AGprEdummsSofer0Pg" version="1" />
		<Service         IdProfile="_nQDnifM1EduRCfi1u_r5eA" idAnno="_nQDnivM1EduRCfi1u_r5eA" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-service/3.3-SNAPSHOT/andromda-profile-service-3.3-SNAPSHOT.uml2#_jl5IZmprEdummsSofer0Pg" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-service/3.3-SNAPSHOT/andromda-profile-service-3.3-SNAPSHOT.uml2#_jl5IZmprEdummsSofer0Pg" version="1" />
		<Webservice  IdProfile="_nQDnjPM1EduRCfi1u_r5eA" idAnno="_nQDnjfM1EduRCfi1u_r5eA" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-webservice/3.3-SNAPSHOT/andromda-profile-webservice-3.3-SNAPSHOT.uml2#_jmC7vWprEdummsSofer0P" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-webservice/3.3-SNAPSHOT/andromda-profile-webservice-3.3-SNAPSHOT.uml2#_jmC7vWprEdummsSofer0Pg" version="1" />
		<Process  IdProfile="_nQDnhvM1EduRCfi1u_r5eA" idAnno="_nQDnh_M1EduRCfi1u_r5eA" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-process/3.3-SNAPSHOT/andromda-profile-process-3.3-SNAPSHOT.uml2#_jl5N02prEdummsSofer0Pg" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-process/3.3-SNAPSHOT/andromda-profile-process-3.3-SNAPSHOT.uml2#_jl5N02prEdummsSofer0Pg" version="1"/>
<Xml IdProfile="_nQDnj_M1EduRCfi1u_r5eA" idAnno="_nQDnkPM1EduRCfi1u_r5eA" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-xml/3.3-SNAPSHOT/andromda-profile-xml-3.3-SNAPSHOT.uml2#_jl5IDmprEdummsSofer0Pg" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-xml/3.3-SNAPSHOT/andromda-profile-xml-3.3-SNAPSHOT.uml2#_jl5IDmprEdummsSofer0Pg" version="1"/>
		<Common IdProfile="_nQDnffM1EduRCfi1u_r5eA" idAnno="_nQDnfvM1EduRCfi1u_r5eA" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-common/3.3-SNAPSHOT/andromda-profile-common-3.3-SNAPSHOT.uml2#_jl5ObWprEdummsSofer0Pg" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-common/3.3-SNAPSHOT/andromda-profile-common-3.3-SNAPSHOT.uml2#_jl5ObWprEdummsSofer0Pg" version="1"/>
		<Meta IdProfile="_nQDngPM1EduRCfi1u_r5eA" idAnno="_nQDngfM1EduRCfi1u_r5eA" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-meta/3.3-SNAPSHOT/andromda-profile-meta-3.3-SNAPSHOT.uml2#_jl5NjGprEdummsSofer0Pg" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-meta/3.3-SNAPSHOT/andromda-profile-meta-3.3-SNAPSHOT.uml2#_jl5NjGprEdummsSofer0P" version="1"/>
	    <Persistance IdProfile="_nQDnk_M1EduRCfi1u_r5eA" idAnno="_nQDnlPM1EduRCfi1u_r5eA" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-persistence/3.3-SNAPSHOT/andromda-profile-persistence-3.3-SNAPSHOT.uml2#_jl5SZmprEdummsSofer0Pg" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-persistence/3.3-SNAPSHOT/andromda-profile-persistence-3.3-SNAPSHOT.uml2#_jl5SZmprEdummsSofer0Pg" version="2"/>
		
	</AndroMDAVersion>     
	<AndroMDAVersion version="3.2-SNAPSHOT">
		<Presentation IdProfile="_rvtf4SK7EduP-_koka1FqA" idAnno="_rvtf4iK7EduP-_koka1FqA"  IdModel="_RgVcjiK2Edu07u_JJk0LDQ" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-presentation/3.2-SNAPSHOT/andromda-profile-presentation-3.2-SNAPSHOT.uml2#_RgVcjiK2Edu07u_JJk0LDQ" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-presentation/3.2-SNAPSHOT/andromda-profile-presentation-3.2-SNAPSHOT.uml2#_RgVcjiK2Edu07u_JJk0LDQ" version="1"/>
		<Service IdProfile="_rvtf5CK7EduP-_koka1FqA" idAnno="_rvtf5SK7EduP-_koka1FqA" IdModel="_RgMRQCK2Edu07u_JJk0LDQ" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-service/3.2-SNAPSHOT/andromda-profile-service-3.2-SNAPSHOT.uml2#_RgMRQCK2Edu07u_JJk0LDQ" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-service/3.2-SNAPSHOT/andromda-profile-service-3.2-SNAPSHOT.uml2#_RgMRQCK2Edu07u_JJk0LDQ" version="1"/>
		<Webservice IdProfile="_rvtf5yK7EduP-_koka1FqA" idAnno="_rvtf6CK7EduP-_koka1FqA"  IdModel="_RgVmWCK2Edu07u_JJk0LDQ" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-webservice/3.2-SNAPSHOT/andromda-profile-webservice-3.2-SNAPSHOT.uml2#_RgVmWCK2Edu07u_JJk0LDQ" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-webservice/3.2-SNAPSHOT/andromda-profile-webservice-3.2-SNAPSHOT.uml2#_RgVmWCK2Edu07u_JJk0LDQ" version="1"/>
		<Process IdProfile="_rvtf6iK7EduP-_koka1FqA" idAnno="_rvtf6yK7EduP-_koka1FqA"  IdModel="_RgfOnSK2Edu07u_JJk0LDQ" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-process/3.2-SNAPSHOT/andromda-profile-process-3.2-SNAPSHOT.uml2#_RgfOnSK2Edu07u_JJk0LDQ" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-process/3.2-SNAPSHOT/andromda-profile-process-3.2-SNAPSHOT.uml2#_RgfOnSK2Edu07u_JJk0LDQ" version="1"/>
		<Xml IdProfile="_rvtf7SK7EduP-_koka1FqA" idAnno="_rvtf7iK7EduP-_koka1FqA"  IdModel="" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-xml/3.2-SNAPSHOT/andromda-profile-xml-3.2-SNAPSHOT.uml2#_RgVfXCK2Edu07u_JJk0LDQ" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-xml/3.2-SNAPSHOT/andromda-profile-xml-3.2-SNAPSHOT.uml2#_RgVfXCK2Edu07u_JJk0LDQ" version="1"/>
		<Common IdProfile="_rvtf8CK7EduP-_koka1FqA" idAnno="_rvtf8SK7EduP-_koka1FqA"  IdModel="" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-common/3.2-SNAPSHOT/andromda-profile-common-3.2-SNAPSHOT.uml2#_RgfPHCK2Edu07u_JJk0LDQ" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-common/3.2-SNAPSHOT/andromda-profile-common-3.2-SNAPSHOT.uml2#_RgfPHCK2Edu07u_JJk0LDQ" version="1"/>
		<Meta IdProfile="_rvtf8yK7EduP-_koka1FqA" idAnno="_rvtf9CK7EduP-_koka1FqA"  IdModel="" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-meta/3.2-SNAPSHOT/andromda-profile-meta-3.2-SNAPSHOT.uml2#_RgVcYiK2Edu07u_JJk0LDQ" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-meta/3.2-SNAPSHOT/andromda-profile-meta-3.2-SNAPSHOT.uml2#_RgVcYiK2Edu07u_JJk0LDQ" version="1"/>
		<Persistance IdProfile="_rvtf9iK7EduP-_koka1FqA" idAnno="_rvtf9yK7EduP-_koka1FqA"  IdModel="" ImportedPackage="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-persistence/3.2-SNAPSHOT/andromda-profile-persistence-3.2-SNAPSHOT.uml2#_RgVfdiK2Edu07u_JJk0LDQ" ImportedProfile="pathmap://m2repository/org/andromda/profiles/emf/uml2/andromda-profile-persistence/3.2-SNAPSHOT/andromda-profile-persistence-3.2-SNAPSHOT.uml2#_RgVfdiK2Edu07u_JJk0LDQ" version="1"/>
	</AndroMDAVersion>
	
</XML_PACKAGE_ID_CONF>
